/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../publicfor_web.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("for_web.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="BezierCircle"
          position={[0, 5.073, 0]}
          rotation={[-Math.PI, 1, -Math.PI]}
          scale={21.878}
        />
        <mesh
          name="Assembled_js_75_use_-_T100-ASM-CW-THRUSTER-R14-4"
          geometry={
            nodes["Assembled_js_75_use_-_T100-ASM-CW-THRUSTER-R14-4"].geometry
          }
          material={materials["Metalic Paint.001"]}
          position={[5.083, 1.371, -3.821]}
          rotation={[-Math.PI / 2, 0, 2.356]}
          scale={0.01}
        />
        <mesh
          name="Assembled_js_75_use_-_T100-ASM-CW-THRUSTER-R14-4001"
          geometry={
            nodes["Assembled_js_75_use_-_T100-ASM-CW-THRUSTER-R14-4001"]
              .geometry
          }
          material={materials["Metalic Paint.001"]}
          position={[1.017, 1.371, -3.815]}
          rotation={[-Math.PI / 2, 0, Math.PI / 4]}
          scale={0.01}
        />
        <mesh
          name="Assembled_js_75_use_-_T100-ASM-CW-THRUSTER-R14-4002"
          geometry={
            nodes["Assembled_js_75_use_-_T100-ASM-CW-THRUSTER-R14-4002"]
              .geometry
          }
          material={materials["Metalic Paint.001"]}
          position={[5.083, 1.371, -0.601]}
          rotation={[-Math.PI / 2, 0, -2.356]}
          scale={0.01}
        />
        <mesh
          name="Assembled_js_75_use_-_T100-ASM-CW-THRUSTER-R14-4003"
          geometry={
            nodes["Assembled_js_75_use_-_T100-ASM-CW-THRUSTER-R14-4003"]
              .geometry
          }
          material={materials["Metalic Paint.001"]}
          position={[0.992, 1.371, -0.609]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 4]}
          scale={0.01}
        />
        <group
          name="JD-12-MetalFrame"
          position={[2.94, 2.63, -2.21]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={-0.011}
        >
          <mesh
            name="JD-12-MetalFrame_1"
            geometry={nodes["JD-12-MetalFrame_1"].geometry}
            material={materials["Material.001"]}
          />
          <mesh
            name="JD-12-MetalFrame_2"
            geometry={nodes["JD-12-MetalFrame_2"].geometry}
            material={materials["Material.004"]}
          />
          <mesh
            name="JD-12-MetalFrame_3"
            geometry={nodes["JD-12-MetalFrame_3"].geometry}
            material={materials["Material.002"]}
          />
          <mesh
            name="JD-12-MetalFrame_4"
            geometry={nodes["JD-12-MetalFrame_4"].geometry}
            material={materials["Material.003"]}
          />
          <group name="MCH_Rotation_target001" scale={-94.937} />
          <group name="MCH_Rotation_target002" scale={-94.937} />
          <group name="MCH_Rotation_target003" scale={-94.937} />
          <group name="MCH_Rotation_target004" scale={-94.937} />
        </group>
        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={materials["White concrete"]}
          position={[3.192, 26.463, -2.128]}
          rotation={[0.036, 1.254, -0.034]}
          scale={[57.147, 26.284, 57.147]}
        >
          <group name="MCH_Rotation_target" scale={[0.013, 0.028, 0.013]} />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("for_web.glb");
